### ISSUE TITLE
Config back-end

### ISSUE THREAD

**Issue by diegovdc** [federacion-de-codigo-al-vuelo/en-vivo#5]
- [x] Servidor de imágenes
- [ ] Creación de entidades básicas de proyecto (evento, roles de usuario, etc.)

**Comment by furenku** [comment]
Se mueve a repo backend https://github.com/federacion-de-codigo-al-vuelo/en-vivo-backend/issues/1

**Comment by furenku** [comment]
Se mueve a repo backend https://github.com/federacion-de-codigo-al-vuelo/en-vivo-backend/issues/1
